### PR TITLE
Reduce specificity of python-dotenv dependency

### PR DESCRIPTION
**Pull request by ap-inflection**
## Description of the change

Changes the python-dotenv dependency version to be either 0.x or 1.x, fixing a poetry version conflict I'm facing.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] Chore (cleanup or minor QOL tweak that has little to no impact on functionality)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by ap-inflection** [comment]
@vvillait88, I was running into an issue with poetry where one dependency I have requires `python-dotenv@~1.0.1` and this library with a dependency which specified <1.

I don't think there was any API change from python-dotenv between 0.X and 1.X, so just bumped it so poetry accepts anything less than version 2.

Ran 

`poetry export -f requirements.txt --dev --output requirements_dev.txt` and
`poetry export -f requirements.txt --output requirements.txt`

which is why the PR is so big

**Comment by vvillait88** [comment]
@ap-inflection Sorry for the delay, for some reason this fell through my notifications.  Looks like there is an issue that breaks our tests when making this change.  We will have to look further into this before merging it in.

**Comment by vvillait88** [comment]
@ap-inflection closing this PR in favor of https://github.com/peopledatalabs/peopledatalabs-python/pull/133 where I have everything working.

**Comment by ap-inflection** [comment]
Perfect, thank you!

**Pull request closed without merging**
